#!/bin/sh

branch=$(git rev-parse --symbolic --abbrev-ref HEAD)
describe=$(git describe --always)

if [ "$branch" == "internal-master" ]
then
  cat > JREngage-Info.plist <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleShortVersionString</key>
	<string>$describe</string>
	<key>JREngage.GitCommit</key>
	<string>$describe</string>
	<key>JREngage.CustomInterface</key>
	<dict>
		<key>DefaultValues</key>
		<dict>
			<key>Authentication.Background.Color.RGBa</key>
			<array>
				<real>0.102</real>
				<real>0.33</real>
				<real>0.48</real>
				<real>0.2</real>
			</array>
		</dict>
		<key>CustomValues</key>
		<dict/>
	</dict>
</dict>
</plist>
PLIST

  if [ -d ./Janrain/JREngage/ ]
  then
    mv JREngage-Info.plist ./Janrain/JREngage/
    git add ./Janrain/JREngage/JREngage-Info.plist
  fi
fi

